In [1]:
import numpy as np
import svm_mlia as svm
import importlib
import matplotlib
import matplotlib.pyplot as plt
importlib.reload(svm)

<module 'svm_mlia' from '/Users/jinxinzhe/Documents/GitHub/machinelearning/svm_mlia.py'>

In [3]:
clf = svm.svm_mlia()
data_train, labels_train = svm.load_img('trainingDigits')
data_test, labels_test = svm.load_img('testDigits')
clf.smoP(data_train, labels_train, 200, 0.001, 100, ('rbf',10))
clf.pred(data_train, labels_train)
clf.pred(data_test, labels_test)

*******the 0 sample*******
L==H
fullset, iter:0 i:0, paris changed 0
*******the 1 sample*******
fullset, iter:0 i:1, paris changed 1
*******the 2 sample*******
fullset, iter:0 i:2, paris changed 2
*******the 3 sample*******
fullset, iter:0 i:3, paris changed 3
*******the 4 sample*******
fullset, iter:0 i:4, paris changed 4
*******the 5 sample*******
fullset, iter:0 i:5, paris changed 5
*******the 6 sample*******
L==H
fullset, iter:0 i:6, paris changed 5
*******the 7 sample*******
fullset, iter:0 i:7, paris changed 6
*******the 8 sample*******
fullset, iter:0 i:8, paris changed 7
*******the 9 sample*******
fullset, iter:0 i:9, paris changed 8
*******the 10 sample*******
fullset, iter:0 i:10, paris changed 8
*******the 11 sample*******
fullset, iter:0 i:11, paris changed 8
*******the 12 sample*******
fullset, iter:0 i:12, paris changed 8
*******the 13 sample*******
fullset, iter:0 i:13, paris changed 9
*******the 14 sample*******
fullset, iter:0 i:14, paris changed 10
*******the 15 sampl

fullset, iter:0 i:144, paris changed 11
*******the 145 sample*******
fullset, iter:0 i:145, paris changed 11
*******the 146 sample*******
L==H
fullset, iter:0 i:146, paris changed 11
*******the 147 sample*******
L==H
fullset, iter:0 i:147, paris changed 11
*******the 148 sample*******
L==H
fullset, iter:0 i:148, paris changed 11
*******the 149 sample*******
L==H
fullset, iter:0 i:149, paris changed 11
*******the 150 sample*******
L==H
fullset, iter:0 i:150, paris changed 11
*******the 151 sample*******
L==H
fullset, iter:0 i:151, paris changed 11
*******the 152 sample*******
L==H
fullset, iter:0 i:152, paris changed 11
*******the 153 sample*******
L==H
fullset, iter:0 i:153, paris changed 11
*******the 154 sample*******
L==H
fullset, iter:0 i:154, paris changed 11
*******the 155 sample*******
L==H
fullset, iter:0 i:155, paris changed 11
*******the 156 sample*******
L==H
fullset, iter:0 i:156, paris changed 11
*******the 157 sample*******
L==H
fullset, iter:0 i:157, paris changed 11
***

L==H
fullset, iter:0 i:258, paris changed 11
*******the 259 sample*******
L==H
fullset, iter:0 i:259, paris changed 11
*******the 260 sample*******
L==H
fullset, iter:0 i:260, paris changed 11
*******the 261 sample*******
L==H
fullset, iter:0 i:261, paris changed 11
*******the 262 sample*******
L==H
fullset, iter:0 i:262, paris changed 11
*******the 263 sample*******
L==H
fullset, iter:0 i:263, paris changed 11
*******the 264 sample*******
L==H
fullset, iter:0 i:264, paris changed 11
*******the 265 sample*******
L==H
fullset, iter:0 i:265, paris changed 11
*******the 266 sample*******
L==H
fullset, iter:0 i:266, paris changed 11
*******the 267 sample*******
L==H
fullset, iter:0 i:267, paris changed 11
*******the 268 sample*******
L==H
fullset, iter:0 i:268, paris changed 11
*******the 269 sample*******
L==H
fullset, iter:0 i:269, paris changed 11
*******the 270 sample*******
L==H
fullset, iter:0 i:270, paris changed 11
*******the 271 sample*******
L==H
fullset, iter:0 i:271, paris chan

L==H
fullset, iter:0 i:378, paris changed 11
*******the 379 sample*******
L==H
fullset, iter:0 i:379, paris changed 11
*******the 380 sample*******
L==H
fullset, iter:0 i:380, paris changed 11
*******the 381 sample*******
L==H
fullset, iter:0 i:381, paris changed 11
*******the 382 sample*******
L==H
fullset, iter:0 i:382, paris changed 11
*******the 383 sample*******
L==H
fullset, iter:0 i:383, paris changed 11
*******the 384 sample*******
L==H
fullset, iter:0 i:384, paris changed 11
*******the 385 sample*******
L==H
fullset, iter:0 i:385, paris changed 11
*******the 386 sample*******
L==H
fullset, iter:0 i:386, paris changed 11
*******the 387 sample*******
L==H
fullset, iter:0 i:387, paris changed 11
*******the 388 sample*******
L==H
fullset, iter:0 i:388, paris changed 11
*******the 389 sample*******
L==H
fullset, iter:0 i:389, paris changed 11
*******the 390 sample*******
L==H
fullset, iter:0 i:390, paris changed 11
*******the 391 sample*******
L==H
fullset, iter:0 i:391, paris chan

L==H
fullset, iter:0 i:494, paris changed 11
*******the 495 sample*******
L==H
fullset, iter:0 i:495, paris changed 11
*******the 496 sample*******
L==H
fullset, iter:0 i:496, paris changed 11
*******the 497 sample*******
L==H
fullset, iter:0 i:497, paris changed 11
*******the 498 sample*******
L==H
fullset, iter:0 i:498, paris changed 11
*******the 499 sample*******
L==H
fullset, iter:0 i:499, paris changed 11
*******the 500 sample*******
L==H
fullset, iter:0 i:500, paris changed 11
*******the 501 sample*******
L==H
fullset, iter:0 i:501, paris changed 11
*******the 502 sample*******
L==H
fullset, iter:0 i:502, paris changed 11
*******the 503 sample*******
L==H
fullset, iter:0 i:503, paris changed 11
*******the 504 sample*******
L==H
fullset, iter:0 i:504, paris changed 11
*******the 505 sample*******
L==H
fullset, iter:0 i:505, paris changed 11
*******the 506 sample*******
L==H
fullset, iter:0 i:506, paris changed 11
*******the 507 sample*******
L==H
fullset, iter:0 i:507, paris chan

L==H
fullset, iter:0 i:607, paris changed 11
*******the 608 sample*******
L==H
fullset, iter:0 i:608, paris changed 11
*******the 609 sample*******
L==H
fullset, iter:0 i:609, paris changed 11
*******the 610 sample*******
L==H
fullset, iter:0 i:610, paris changed 11
*******the 611 sample*******
L==H
fullset, iter:0 i:611, paris changed 11
*******the 612 sample*******
L==H
fullset, iter:0 i:612, paris changed 11
*******the 613 sample*******
L==H
fullset, iter:0 i:613, paris changed 11
*******the 614 sample*******
L==H
fullset, iter:0 i:614, paris changed 11
*******the 615 sample*******
L==H
fullset, iter:0 i:615, paris changed 11
*******the 616 sample*******
L==H
fullset, iter:0 i:616, paris changed 11
*******the 617 sample*******
L==H
fullset, iter:0 i:617, paris changed 11
*******the 618 sample*******
L==H
fullset, iter:0 i:618, paris changed 11
*******the 619 sample*******
L==H
fullset, iter:0 i:619, paris changed 11
*******the 620 sample*******
L==H
fullset, iter:0 i:620, paris chan

L==H
fullset, iter:0 i:719, paris changed 11
*******the 720 sample*******
L==H
fullset, iter:0 i:720, paris changed 11
*******the 721 sample*******
L==H
fullset, iter:0 i:721, paris changed 11
*******the 722 sample*******
L==H
fullset, iter:0 i:722, paris changed 11
*******the 723 sample*******
L==H
fullset, iter:0 i:723, paris changed 11
*******the 724 sample*******
L==H
fullset, iter:0 i:724, paris changed 11
*******the 725 sample*******
L==H
fullset, iter:0 i:725, paris changed 11
*******the 726 sample*******
L==H
fullset, iter:0 i:726, paris changed 11
*******the 727 sample*******
L==H
fullset, iter:0 i:727, paris changed 11
*******the 728 sample*******
L==H
fullset, iter:0 i:728, paris changed 11
*******the 729 sample*******
L==H
fullset, iter:0 i:729, paris changed 11
*******the 730 sample*******
L==H
fullset, iter:0 i:730, paris changed 11
*******the 731 sample*******
L==H
fullset, iter:0 i:731, paris changed 11
*******the 732 sample*******
L==H
fullset, iter:0 i:732, paris chan

L==H
fullset, iter:0 i:831, paris changed 11
*******the 832 sample*******
L==H
fullset, iter:0 i:832, paris changed 11
*******the 833 sample*******
L==H
fullset, iter:0 i:833, paris changed 11
*******the 834 sample*******
L==H
fullset, iter:0 i:834, paris changed 11
*******the 835 sample*******
L==H
fullset, iter:0 i:835, paris changed 11
*******the 836 sample*******
L==H
fullset, iter:0 i:836, paris changed 11
*******the 837 sample*******
L==H
fullset, iter:0 i:837, paris changed 11
*******the 838 sample*******
L==H
fullset, iter:0 i:838, paris changed 11
*******the 839 sample*******
L==H
fullset, iter:0 i:839, paris changed 11
*******the 840 sample*******
L==H
fullset, iter:0 i:840, paris changed 11
*******the 841 sample*******
L==H
fullset, iter:0 i:841, paris changed 11
*******the 842 sample*******
L==H
fullset, iter:0 i:842, paris changed 11
*******the 843 sample*******
L==H
fullset, iter:0 i:843, paris changed 11
*******the 844 sample*******
L==H
fullset, iter:0 i:844, paris chan

L==H
fullset, iter:0 i:944, paris changed 11
*******the 945 sample*******
L==H
fullset, iter:0 i:945, paris changed 11
*******the 946 sample*******
L==H
fullset, iter:0 i:946, paris changed 11
*******the 947 sample*******
L==H
fullset, iter:0 i:947, paris changed 11
*******the 948 sample*******
L==H
fullset, iter:0 i:948, paris changed 11
*******the 949 sample*******
L==H
fullset, iter:0 i:949, paris changed 11
*******the 950 sample*******
L==H
fullset, iter:0 i:950, paris changed 11
*******the 951 sample*******
L==H
fullset, iter:0 i:951, paris changed 11
*******the 952 sample*******
L==H
fullset, iter:0 i:952, paris changed 11
*******the 953 sample*******
L==H
fullset, iter:0 i:953, paris changed 11
*******the 954 sample*******
L==H
fullset, iter:0 i:954, paris changed 11
*******the 955 sample*******
L==H
fullset, iter:0 i:955, paris changed 11
*******the 956 sample*******
L==H
fullset, iter:0 i:956, paris changed 11
*******the 957 sample*******
L==H
fullset, iter:0 i:957, paris chan

L==H
fullset, iter:0 i:1056, paris changed 11
*******the 1057 sample*******
L==H
fullset, iter:0 i:1057, paris changed 11
*******the 1058 sample*******
L==H
fullset, iter:0 i:1058, paris changed 11
*******the 1059 sample*******
L==H
fullset, iter:0 i:1059, paris changed 11
*******the 1060 sample*******
L==H
fullset, iter:0 i:1060, paris changed 11
*******the 1061 sample*******
L==H
fullset, iter:0 i:1061, paris changed 11
*******the 1062 sample*******
L==H
fullset, iter:0 i:1062, paris changed 11
*******the 1063 sample*******
L==H
fullset, iter:0 i:1063, paris changed 11
*******the 1064 sample*******
L==H
fullset, iter:0 i:1064, paris changed 11
*******the 1065 sample*******
L==H
fullset, iter:0 i:1065, paris changed 11
*******the 1066 sample*******
L==H
fullset, iter:0 i:1066, paris changed 11
*******the 1067 sample*******
L==H
fullset, iter:0 i:1067, paris changed 11
*******the 1068 sample*******
L==H
fullset, iter:0 i:1068, paris changed 11
*******the 1069 sample*******
L==H
fullset

L==H
fullset, iter:0 i:1164, paris changed 11
*******the 1165 sample*******
L==H
fullset, iter:0 i:1165, paris changed 11
*******the 1166 sample*******
L==H
fullset, iter:0 i:1166, paris changed 11
*******the 1167 sample*******
L==H
fullset, iter:0 i:1167, paris changed 11
*******the 1168 sample*******
L==H
fullset, iter:0 i:1168, paris changed 11
*******the 1169 sample*******
L==H
fullset, iter:0 i:1169, paris changed 11
*******the 1170 sample*******
L==H
fullset, iter:0 i:1170, paris changed 11
*******the 1171 sample*******
L==H
fullset, iter:0 i:1171, paris changed 11
*******the 1172 sample*******
L==H
fullset, iter:0 i:1172, paris changed 11
*******the 1173 sample*******
L==H
fullset, iter:0 i:1173, paris changed 11
*******the 1174 sample*******
L==H
fullset, iter:0 i:1174, paris changed 11
*******the 1175 sample*******
L==H
fullset, iter:0 i:1175, paris changed 11
*******the 1176 sample*******
L==H
fullset, iter:0 i:1176, paris changed 11
*******the 1177 sample*******
L==H
fullset

L==H
fullset, iter:0 i:1273, paris changed 11
*******the 1274 sample*******
L==H
fullset, iter:0 i:1274, paris changed 11
*******the 1275 sample*******
L==H
fullset, iter:0 i:1275, paris changed 11
*******the 1276 sample*******
L==H
fullset, iter:0 i:1276, paris changed 11
*******the 1277 sample*******
L==H
fullset, iter:0 i:1277, paris changed 11
*******the 1278 sample*******
L==H
fullset, iter:0 i:1278, paris changed 11
*******the 1279 sample*******
L==H
fullset, iter:0 i:1279, paris changed 11
*******the 1280 sample*******
L==H
fullset, iter:0 i:1280, paris changed 11
*******the 1281 sample*******
L==H
fullset, iter:0 i:1281, paris changed 11
*******the 1282 sample*******
L==H
fullset, iter:0 i:1282, paris changed 11
*******the 1283 sample*******
L==H
fullset, iter:0 i:1283, paris changed 11
*******the 1284 sample*******
L==H
fullset, iter:0 i:1284, paris changed 11
*******the 1285 sample*******
L==H
fullset, iter:0 i:1285, paris changed 11
*******the 1286 sample*******
L==H
fullset

L==H
fullset, iter:0 i:1383, paris changed 11
*******the 1384 sample*******
L==H
fullset, iter:0 i:1384, paris changed 11
*******the 1385 sample*******
L==H
fullset, iter:0 i:1385, paris changed 11
*******the 1386 sample*******
L==H
fullset, iter:0 i:1386, paris changed 11
*******the 1387 sample*******
L==H
fullset, iter:0 i:1387, paris changed 11
*******the 1388 sample*******
L==H
fullset, iter:0 i:1388, paris changed 11
*******the 1389 sample*******
L==H
fullset, iter:0 i:1389, paris changed 11
*******the 1390 sample*******
L==H
fullset, iter:0 i:1390, paris changed 11
*******the 1391 sample*******
L==H
fullset, iter:0 i:1391, paris changed 11
*******the 1392 sample*******
L==H
fullset, iter:0 i:1392, paris changed 11
*******the 1393 sample*******
L==H
fullset, iter:0 i:1393, paris changed 11
*******the 1394 sample*******
L==H
fullset, iter:0 i:1394, paris changed 11
*******the 1395 sample*******
L==H
fullset, iter:0 i:1395, paris changed 11
*******the 1396 sample*******
L==H
fullset

L==H
fullset, iter:0 i:1491, paris changed 11
*******the 1492 sample*******
L==H
fullset, iter:0 i:1492, paris changed 11
*******the 1493 sample*******
L==H
fullset, iter:0 i:1493, paris changed 11
*******the 1494 sample*******
L==H
fullset, iter:0 i:1494, paris changed 11
*******the 1495 sample*******
L==H
fullset, iter:0 i:1495, paris changed 11
*******the 1496 sample*******
L==H
fullset, iter:0 i:1496, paris changed 11
*******the 1497 sample*******
L==H
fullset, iter:0 i:1497, paris changed 11
*******the 1498 sample*******
L==H
fullset, iter:0 i:1498, paris changed 11
*******the 1499 sample*******
L==H
fullset, iter:0 i:1499, paris changed 11
*******the 1500 sample*******
L==H
fullset, iter:0 i:1500, paris changed 11
*******the 1501 sample*******
L==H
fullset, iter:0 i:1501, paris changed 11
*******the 1502 sample*******
L==H
fullset, iter:0 i:1502, paris changed 11
*******the 1503 sample*******
L==H
fullset, iter:0 i:1503, paris changed 11
*******the 1504 sample*******
L==H
fullset

L==H
fullset, iter:0 i:1600, paris changed 11
*******the 1601 sample*******
L==H
fullset, iter:0 i:1601, paris changed 11
*******the 1602 sample*******
L==H
fullset, iter:0 i:1602, paris changed 11
*******the 1603 sample*******
L==H
fullset, iter:0 i:1603, paris changed 11
*******the 1604 sample*******
L==H
fullset, iter:0 i:1604, paris changed 11
*******the 1605 sample*******
L==H
fullset, iter:0 i:1605, paris changed 11
*******the 1606 sample*******
L==H
fullset, iter:0 i:1606, paris changed 11
*******the 1607 sample*******
L==H
fullset, iter:0 i:1607, paris changed 11
*******the 1608 sample*******
L==H
fullset, iter:0 i:1608, paris changed 11
*******the 1609 sample*******
L==H
fullset, iter:0 i:1609, paris changed 11
*******the 1610 sample*******
L==H
fullset, iter:0 i:1610, paris changed 11
*******the 1611 sample*******
L==H
fullset, iter:0 i:1611, paris changed 11
*******the 1612 sample*******
L==H
fullset, iter:0 i:1612, paris changed 11
*******the 1613 sample*******
L==H
fullset

L==H
fullset, iter:0 i:1710, paris changed 11
*******the 1711 sample*******
L==H
fullset, iter:0 i:1711, paris changed 11
*******the 1712 sample*******
L==H
fullset, iter:0 i:1712, paris changed 11
*******the 1713 sample*******
L==H
fullset, iter:0 i:1713, paris changed 11
*******the 1714 sample*******
L==H
fullset, iter:0 i:1714, paris changed 11
*******the 1715 sample*******
L==H
fullset, iter:0 i:1715, paris changed 11
*******the 1716 sample*******
L==H
fullset, iter:0 i:1716, paris changed 11
*******the 1717 sample*******
L==H
fullset, iter:0 i:1717, paris changed 11
*******the 1718 sample*******
L==H
fullset, iter:0 i:1718, paris changed 11
*******the 1719 sample*******
L==H
fullset, iter:0 i:1719, paris changed 11
*******the 1720 sample*******
L==H
fullset, iter:0 i:1720, paris changed 11
*******the 1721 sample*******
L==H
fullset, iter:0 i:1721, paris changed 11
*******the 1722 sample*******
L==H
fullset, iter:0 i:1722, paris changed 11
*******the 1723 sample*******
L==H
fullset

j not moving enough
fullset, iter:0 i:1818, paris changed 65
*******the 1819 sample*******
fullset, iter:0 i:1819, paris changed 66
*******the 1820 sample*******
j not moving enough
fullset, iter:0 i:1820, paris changed 66
*******the 1821 sample*******
j not moving enough
fullset, iter:0 i:1821, paris changed 66
*******the 1822 sample*******
fullset, iter:0 i:1822, paris changed 67
*******the 1823 sample*******
fullset, iter:0 i:1823, paris changed 68
*******the 1824 sample*******
fullset, iter:0 i:1824, paris changed 69
*******the 1825 sample*******
fullset, iter:0 i:1825, paris changed 70
*******the 1826 sample*******
j not moving enough
fullset, iter:0 i:1826, paris changed 70
*******the 1827 sample*******
j not moving enough
fullset, iter:0 i:1827, paris changed 70
*******the 1828 sample*******
fullset, iter:0 i:1828, paris changed 71
*******the 1829 sample*******
fullset, iter:0 i:1829, paris changed 72
*******the 1830 sample*******
fullset, iter:0 i:1830, paris changed 73
*******

j not moving enough
fullset, iter:0 i:1924, paris changed 112
*******the 1925 sample*******
fullset, iter:0 i:1925, paris changed 112
*******the 1926 sample*******
fullset, iter:0 i:1926, paris changed 113
*******the 1927 sample*******
j not moving enough
fullset, iter:0 i:1927, paris changed 113
*******the 1928 sample*******
j not moving enough
fullset, iter:0 i:1928, paris changed 113
*******the 1929 sample*******
j not moving enough
fullset, iter:0 i:1929, paris changed 113
*******the 1930 sample*******
fullset, iter:0 i:1930, paris changed 114
*******the 1931 sample*******
fullset, iter:0 i:1931, paris changed 114
*******the 1932 sample*******
j not moving enough
fullset, iter:0 i:1932, paris changed 114
*******the 1933 sample*******
j not moving enough
fullset, iter:0 i:1933, paris changed 114
iteration number: 1
*******the 1 sample*******
j not moving enough
non-bound, iter:1 i:1, paris changed 0
*******the 2 sample*******
j not moving enough
non-bound, iter:1 i:2, paris changed 

j not moving enough
non-bound, iter:1 i:1608, paris changed 3
*******the 1610 sample*******
j not moving enough
non-bound, iter:1 i:1610, paris changed 3
*******the 1627 sample*******
j not moving enough
non-bound, iter:1 i:1627, paris changed 3
*******the 1630 sample*******
j not moving enough
non-bound, iter:1 i:1630, paris changed 3
*******the 1633 sample*******
j not moving enough
non-bound, iter:1 i:1633, paris changed 3
*******the 1663 sample*******
j not moving enough
non-bound, iter:1 i:1663, paris changed 3
*******the 1681 sample*******
j not moving enough
non-bound, iter:1 i:1681, paris changed 3
*******the 1683 sample*******
j not moving enough
non-bound, iter:1 i:1683, paris changed 3
*******the 1689 sample*******
j not moving enough
non-bound, iter:1 i:1689, paris changed 3
*******the 1708 sample*******
j not moving enough
non-bound, iter:1 i:1708, paris changed 3
*******the 1730 sample*******
j not moving enough
non-bound, iter:1 i:1730, paris changed 3
*******the 1731 sa

j not moving enough
non-bound, iter:1 i:1873, paris changed 12
*******the 1874 sample*******
j not moving enough
non-bound, iter:1 i:1874, paris changed 12
*******the 1875 sample*******
non-bound, iter:1 i:1875, paris changed 13
*******the 1881 sample*******
j not moving enough
non-bound, iter:1 i:1881, paris changed 13
*******the 1884 sample*******
j not moving enough
non-bound, iter:1 i:1884, paris changed 13
*******the 1885 sample*******
j not moving enough
non-bound, iter:1 i:1885, paris changed 13
*******the 1894 sample*******
j not moving enough
non-bound, iter:1 i:1894, paris changed 13
*******the 1895 sample*******
j not moving enough
non-bound, iter:1 i:1895, paris changed 13
*******the 1896 sample*******
j not moving enough
non-bound, iter:1 i:1896, paris changed 13
*******the 1898 sample*******
j not moving enough
non-bound, iter:1 i:1898, paris changed 13
*******the 1899 sample*******
j not moving enough
non-bound, iter:1 i:1899, paris changed 13
*******the 1902 sample*****

j not moving enough
non-bound, iter:2 i:1087, paris changed 0
*******the 1107 sample*******
j not moving enough
non-bound, iter:2 i:1107, paris changed 0
*******the 1108 sample*******
j not moving enough
non-bound, iter:2 i:1108, paris changed 0
*******the 1110 sample*******
j not moving enough
non-bound, iter:2 i:1110, paris changed 0
*******the 1111 sample*******
j not moving enough
non-bound, iter:2 i:1111, paris changed 0
*******the 1112 sample*******
j not moving enough
non-bound, iter:2 i:1112, paris changed 0
*******the 1358 sample*******
j not moving enough
non-bound, iter:2 i:1358, paris changed 0
*******the 1372 sample*******
j not moving enough
non-bound, iter:2 i:1372, paris changed 0
*******the 1374 sample*******
non-bound, iter:2 i:1374, paris changed 0
*******the 1390 sample*******
j not moving enough
non-bound, iter:2 i:1390, paris changed 0
*******the 1396 sample*******
j not moving enough
non-bound, iter:2 i:1396, paris changed 0
*******the 1437 sample*******
j not mo

j not moving enough
non-bound, iter:2 i:1838, paris changed 1
*******the 1842 sample*******
j not moving enough
non-bound, iter:2 i:1842, paris changed 1
*******the 1843 sample*******
j not moving enough
non-bound, iter:2 i:1843, paris changed 1
*******the 1844 sample*******
j not moving enough
non-bound, iter:2 i:1844, paris changed 1
*******the 1847 sample*******
j not moving enough
non-bound, iter:2 i:1847, paris changed 1
*******the 1848 sample*******
j not moving enough
non-bound, iter:2 i:1848, paris changed 1
*******the 1849 sample*******
j not moving enough
non-bound, iter:2 i:1849, paris changed 1
*******the 1850 sample*******
j not moving enough
non-bound, iter:2 i:1850, paris changed 1
*******the 1851 sample*******
j not moving enough
non-bound, iter:2 i:1851, paris changed 1
*******the 1853 sample*******
j not moving enough
non-bound, iter:2 i:1853, paris changed 1
*******the 1854 sample*******
j not moving enough
non-bound, iter:2 i:1854, paris changed 1
*******the 1856 sa

*******the 832 sample*******
j not moving enough
non-bound, iter:3 i:832, paris changed 0
*******the 834 sample*******
j not moving enough
non-bound, iter:3 i:834, paris changed 0
*******the 835 sample*******
j not moving enough
non-bound, iter:3 i:835, paris changed 0
*******the 852 sample*******
j not moving enough
non-bound, iter:3 i:852, paris changed 0
*******the 875 sample*******
j not moving enough
non-bound, iter:3 i:875, paris changed 0
*******the 879 sample*******
j not moving enough
non-bound, iter:3 i:879, paris changed 0
*******the 890 sample*******
non-bound, iter:3 i:890, paris changed 0
*******the 901 sample*******
j not moving enough
non-bound, iter:3 i:901, paris changed 0
*******the 912 sample*******
j not moving enough
non-bound, iter:3 i:912, paris changed 0
*******the 923 sample*******
j not moving enough
non-bound, iter:3 i:923, paris changed 0
*******the 961 sample*******
j not moving enough
non-bound, iter:3 i:961, paris changed 0
*******the 967 sample*******
j

j not moving enough
non-bound, iter:3 i:1785, paris changed 1
*******the 1786 sample*******
j not moving enough
non-bound, iter:3 i:1786, paris changed 1
*******the 1787 sample*******
j not moving enough
non-bound, iter:3 i:1787, paris changed 1
*******the 1790 sample*******
j not moving enough
non-bound, iter:3 i:1790, paris changed 1
*******the 1791 sample*******
j not moving enough
non-bound, iter:3 i:1791, paris changed 1
*******the 1792 sample*******
j not moving enough
non-bound, iter:3 i:1792, paris changed 1
*******the 1794 sample*******
j not moving enough
non-bound, iter:3 i:1794, paris changed 1
*******the 1800 sample*******
j not moving enough
non-bound, iter:3 i:1800, paris changed 1
*******the 1809 sample*******
j not moving enough
non-bound, iter:3 i:1809, paris changed 1
*******the 1810 sample*******
j not moving enough
non-bound, iter:3 i:1810, paris changed 1
*******the 1816 sample*******
j not moving enough
non-bound, iter:3 i:1816, paris changed 1
*******the 1819 sa

j not moving enough
non-bound, iter:4 i:612, paris changed 0
*******the 618 sample*******
j not moving enough
non-bound, iter:4 i:618, paris changed 0
*******the 625 sample*******
j not moving enough
non-bound, iter:4 i:625, paris changed 0
*******the 654 sample*******
j not moving enough
non-bound, iter:4 i:654, paris changed 0
*******the 655 sample*******
j not moving enough
non-bound, iter:4 i:655, paris changed 0
*******the 660 sample*******
j not moving enough
non-bound, iter:4 i:660, paris changed 0
*******the 691 sample*******
j not moving enough
non-bound, iter:4 i:691, paris changed 0
*******the 710 sample*******
j not moving enough
non-bound, iter:4 i:710, paris changed 0
*******the 724 sample*******
non-bound, iter:4 i:724, paris changed 0
*******the 727 sample*******
j not moving enough
non-bound, iter:4 i:727, paris changed 0
*******the 737 sample*******
j not moving enough
non-bound, iter:4 i:737, paris changed 0
*******the 744 sample*******
j not moving enough
non-bound,

j not moving enough
non-bound, iter:4 i:1750, paris changed 0
*******the 1753 sample*******
j not moving enough
non-bound, iter:4 i:1753, paris changed 0
*******the 1754 sample*******
j not moving enough
non-bound, iter:4 i:1754, paris changed 0
*******the 1755 sample*******
j not moving enough
non-bound, iter:4 i:1755, paris changed 0
*******the 1757 sample*******
j not moving enough
non-bound, iter:4 i:1757, paris changed 0
*******the 1758 sample*******
j not moving enough
non-bound, iter:4 i:1758, paris changed 0
*******the 1765 sample*******
j not moving enough
non-bound, iter:4 i:1765, paris changed 0
*******the 1766 sample*******
j not moving enough
non-bound, iter:4 i:1766, paris changed 0
*******the 1767 sample*******
j not moving enough
non-bound, iter:4 i:1767, paris changed 0
*******the 1768 sample*******
j not moving enough
non-bound, iter:4 i:1768, paris changed 0
*******the 1769 sample*******
j not moving enough
non-bound, iter:4 i:1769, paris changed 0
*******the 1770 sa

L==H
fullset, iter:5 i:11, paris changed 0
*******the 12 sample*******
L==H
fullset, iter:5 i:12, paris changed 0
*******the 13 sample*******
j not moving enough
fullset, iter:5 i:13, paris changed 0
*******the 14 sample*******
j not moving enough
fullset, iter:5 i:14, paris changed 0
*******the 15 sample*******
j not moving enough
fullset, iter:5 i:15, paris changed 0
*******the 16 sample*******
L==H
fullset, iter:5 i:16, paris changed 0
*******the 17 sample*******
fullset, iter:5 i:17, paris changed 0
*******the 18 sample*******
L==H
fullset, iter:5 i:18, paris changed 0
*******the 19 sample*******
fullset, iter:5 i:19, paris changed 0
*******the 20 sample*******
L==H
fullset, iter:5 i:20, paris changed 0
*******the 21 sample*******
L==H
fullset, iter:5 i:21, paris changed 0
*******the 22 sample*******
fullset, iter:5 i:22, paris changed 0
*******the 23 sample*******
L==H
fullset, iter:5 i:23, paris changed 0
*******the 24 sample*******
L==H
fullset, iter:5 i:24, paris changed 0
****

j not moving enough
fullset, iter:5 i:136, paris changed 0
*******the 137 sample*******
fullset, iter:5 i:137, paris changed 0
*******the 138 sample*******
fullset, iter:5 i:138, paris changed 0
*******the 139 sample*******
L==H
fullset, iter:5 i:139, paris changed 0
*******the 140 sample*******
fullset, iter:5 i:140, paris changed 0
*******the 141 sample*******
L==H
fullset, iter:5 i:141, paris changed 0
*******the 142 sample*******
fullset, iter:5 i:142, paris changed 0
*******the 143 sample*******
L==H
fullset, iter:5 i:143, paris changed 0
*******the 144 sample*******
fullset, iter:5 i:144, paris changed 0
*******the 145 sample*******
fullset, iter:5 i:145, paris changed 0
*******the 146 sample*******
L==H
fullset, iter:5 i:146, paris changed 0
*******the 147 sample*******
fullset, iter:5 i:147, paris changed 0
*******the 148 sample*******
fullset, iter:5 i:148, paris changed 0
*******the 149 sample*******
fullset, iter:5 i:149, paris changed 0
*******the 150 sample*******
fullset,

L==H
fullset, iter:5 i:264, paris changed 0
*******the 265 sample*******
fullset, iter:5 i:265, paris changed 0
*******the 266 sample*******
fullset, iter:5 i:266, paris changed 0
*******the 267 sample*******
fullset, iter:5 i:267, paris changed 0
*******the 268 sample*******
fullset, iter:5 i:268, paris changed 0
*******the 269 sample*******
fullset, iter:5 i:269, paris changed 0
*******the 270 sample*******
j not moving enough
fullset, iter:5 i:270, paris changed 0
*******the 271 sample*******
L==H
fullset, iter:5 i:271, paris changed 0
*******the 272 sample*******
L==H
fullset, iter:5 i:272, paris changed 0
*******the 273 sample*******
fullset, iter:5 i:273, paris changed 0
*******the 274 sample*******
j not moving enough
fullset, iter:5 i:274, paris changed 0
*******the 275 sample*******
fullset, iter:5 i:275, paris changed 0
*******the 276 sample*******
fullset, iter:5 i:276, paris changed 0
*******the 277 sample*******
fullset, iter:5 i:277, paris changed 0
*******the 278 sample*

L==H
fullset, iter:5 i:387, paris changed 0
*******the 388 sample*******
fullset, iter:5 i:388, paris changed 0
*******the 389 sample*******
fullset, iter:5 i:389, paris changed 0
*******the 390 sample*******
fullset, iter:5 i:390, paris changed 0
*******the 391 sample*******
fullset, iter:5 i:391, paris changed 0
*******the 392 sample*******
fullset, iter:5 i:392, paris changed 0
*******the 393 sample*******
fullset, iter:5 i:393, paris changed 0
*******the 394 sample*******
fullset, iter:5 i:394, paris changed 0
*******the 395 sample*******
fullset, iter:5 i:395, paris changed 0
*******the 396 sample*******
fullset, iter:5 i:396, paris changed 0
*******the 397 sample*******
fullset, iter:5 i:397, paris changed 0
*******the 398 sample*******
fullset, iter:5 i:398, paris changed 0
*******the 399 sample*******
fullset, iter:5 i:399, paris changed 0
*******the 400 sample*******
fullset, iter:5 i:400, paris changed 0
*******the 401 sample*******
fullset, iter:5 i:401, paris changed 0
****

L==H
fullset, iter:5 i:546, paris changed 0
*******the 547 sample*******
fullset, iter:5 i:547, paris changed 0
*******the 548 sample*******
fullset, iter:5 i:548, paris changed 0
*******the 549 sample*******
fullset, iter:5 i:549, paris changed 0
*******the 550 sample*******
fullset, iter:5 i:550, paris changed 0
*******the 551 sample*******
j not moving enough
fullset, iter:5 i:551, paris changed 0
*******the 552 sample*******
L==H
fullset, iter:5 i:552, paris changed 0
*******the 553 sample*******
fullset, iter:5 i:553, paris changed 0
*******the 554 sample*******
fullset, iter:5 i:554, paris changed 0
*******the 555 sample*******
fullset, iter:5 i:555, paris changed 0
*******the 556 sample*******
fullset, iter:5 i:556, paris changed 0
*******the 557 sample*******
fullset, iter:5 i:557, paris changed 0
*******the 558 sample*******
fullset, iter:5 i:558, paris changed 0
*******the 559 sample*******
fullset, iter:5 i:559, paris changed 0
*******the 560 sample*******
fullset, iter:5 i:

L==H
fullset, iter:5 i:668, paris changed 0
*******the 669 sample*******
fullset, iter:5 i:669, paris changed 0
*******the 670 sample*******
fullset, iter:5 i:670, paris changed 0
*******the 671 sample*******
fullset, iter:5 i:671, paris changed 0
*******the 672 sample*******
fullset, iter:5 i:672, paris changed 0
*******the 673 sample*******
L==H
fullset, iter:5 i:673, paris changed 0
*******the 674 sample*******
fullset, iter:5 i:674, paris changed 0
*******the 675 sample*******
fullset, iter:5 i:675, paris changed 0
*******the 676 sample*******
L==H
fullset, iter:5 i:676, paris changed 0
*******the 677 sample*******
fullset, iter:5 i:677, paris changed 0
*******the 678 sample*******
fullset, iter:5 i:678, paris changed 0
*******the 679 sample*******
fullset, iter:5 i:679, paris changed 0
*******the 680 sample*******
fullset, iter:5 i:680, paris changed 0
*******the 681 sample*******
fullset, iter:5 i:681, paris changed 0
*******the 682 sample*******
L==H
fullset, iter:5 i:682, paris

L==H
fullset, iter:5 i:789, paris changed 0
*******the 790 sample*******
fullset, iter:5 i:790, paris changed 0
*******the 791 sample*******
L==H
fullset, iter:5 i:791, paris changed 0
*******the 792 sample*******
fullset, iter:5 i:792, paris changed 0
*******the 793 sample*******
fullset, iter:5 i:793, paris changed 0
*******the 794 sample*******
fullset, iter:5 i:794, paris changed 0
*******the 795 sample*******
fullset, iter:5 i:795, paris changed 0
*******the 796 sample*******
fullset, iter:5 i:796, paris changed 0
*******the 797 sample*******
fullset, iter:5 i:797, paris changed 0
*******the 798 sample*******
fullset, iter:5 i:798, paris changed 0
*******the 799 sample*******
fullset, iter:5 i:799, paris changed 0
*******the 800 sample*******
fullset, iter:5 i:800, paris changed 0
*******the 801 sample*******
fullset, iter:5 i:801, paris changed 0
*******the 802 sample*******
fullset, iter:5 i:802, paris changed 0
*******the 803 sample*******
fullset, iter:5 i:803, paris changed 0

L==H
fullset, iter:5 i:916, paris changed 0
*******the 917 sample*******
L==H
fullset, iter:5 i:917, paris changed 0
*******the 918 sample*******
fullset, iter:5 i:918, paris changed 0
*******the 919 sample*******
fullset, iter:5 i:919, paris changed 0
*******the 920 sample*******
L==H
fullset, iter:5 i:920, paris changed 0
*******the 921 sample*******
fullset, iter:5 i:921, paris changed 0
*******the 922 sample*******
fullset, iter:5 i:922, paris changed 0
*******the 923 sample*******
j not moving enough
fullset, iter:5 i:923, paris changed 0
*******the 924 sample*******
fullset, iter:5 i:924, paris changed 0
*******the 925 sample*******
fullset, iter:5 i:925, paris changed 0
*******the 926 sample*******
fullset, iter:5 i:926, paris changed 0
*******the 927 sample*******
fullset, iter:5 i:927, paris changed 0
*******the 928 sample*******
fullset, iter:5 i:928, paris changed 0
*******the 929 sample*******
fullset, iter:5 i:929, paris changed 0
*******the 930 sample*******
fullset, iter

L==H
fullset, iter:5 i:1042, paris changed 0
*******the 1043 sample*******
fullset, iter:5 i:1043, paris changed 0
*******the 1044 sample*******
fullset, iter:5 i:1044, paris changed 0
*******the 1045 sample*******
fullset, iter:5 i:1045, paris changed 0
*******the 1046 sample*******
L==H
fullset, iter:5 i:1046, paris changed 0
*******the 1047 sample*******
fullset, iter:5 i:1047, paris changed 0
*******the 1048 sample*******
j not moving enough
fullset, iter:5 i:1048, paris changed 0
*******the 1049 sample*******
L==H
fullset, iter:5 i:1049, paris changed 0
*******the 1050 sample*******
fullset, iter:5 i:1050, paris changed 0
*******the 1051 sample*******
fullset, iter:5 i:1051, paris changed 0
*******the 1052 sample*******
L==H
fullset, iter:5 i:1052, paris changed 0
*******the 1053 sample*******
fullset, iter:5 i:1053, paris changed 0
*******the 1054 sample*******
L==H
fullset, iter:5 i:1054, paris changed 0
*******the 1055 sample*******
L==H
fullset, iter:5 i:1055, paris changed 0


L==H
fullset, iter:5 i:1361, paris changed 0
*******the 1362 sample*******
fullset, iter:5 i:1362, paris changed 0
*******the 1363 sample*******
fullset, iter:5 i:1363, paris changed 0
*******the 1364 sample*******
fullset, iter:5 i:1364, paris changed 0
*******the 1365 sample*******
fullset, iter:5 i:1365, paris changed 0
*******the 1366 sample*******
fullset, iter:5 i:1366, paris changed 0
*******the 1367 sample*******
L==H
fullset, iter:5 i:1367, paris changed 0
*******the 1368 sample*******
fullset, iter:5 i:1368, paris changed 0
*******the 1369 sample*******
fullset, iter:5 i:1369, paris changed 0
*******the 1370 sample*******
L==H
fullset, iter:5 i:1370, paris changed 0
*******the 1371 sample*******
fullset, iter:5 i:1371, paris changed 0
*******the 1372 sample*******
j not moving enough
fullset, iter:5 i:1372, paris changed 0
*******the 1373 sample*******
fullset, iter:5 i:1373, paris changed 0
*******the 1374 sample*******
j not moving enough
fullset, iter:5 i:1374, paris chang

j not moving enough
fullset, iter:5 i:1481, paris changed 0
*******the 1482 sample*******
L==H
fullset, iter:5 i:1482, paris changed 0
*******the 1483 sample*******
L==H
fullset, iter:5 i:1483, paris changed 0
*******the 1484 sample*******
fullset, iter:5 i:1484, paris changed 0
*******the 1485 sample*******
fullset, iter:5 i:1485, paris changed 0
*******the 1486 sample*******
fullset, iter:5 i:1486, paris changed 0
*******the 1487 sample*******
fullset, iter:5 i:1487, paris changed 0
*******the 1488 sample*******
fullset, iter:5 i:1488, paris changed 0
*******the 1489 sample*******
fullset, iter:5 i:1489, paris changed 0
*******the 1490 sample*******
fullset, iter:5 i:1490, paris changed 0
*******the 1491 sample*******
fullset, iter:5 i:1491, paris changed 0
*******the 1492 sample*******
fullset, iter:5 i:1492, paris changed 0
*******the 1493 sample*******
L==H
fullset, iter:5 i:1493, paris changed 0
*******the 1494 sample*******
fullset, iter:5 i:1494, paris changed 0
*******the 1495

L==H
fullset, iter:5 i:1601, paris changed 0
*******the 1602 sample*******
fullset, iter:5 i:1602, paris changed 0
*******the 1603 sample*******
L==H
fullset, iter:5 i:1603, paris changed 0
*******the 1604 sample*******
L==H
fullset, iter:5 i:1604, paris changed 0
*******the 1605 sample*******
fullset, iter:5 i:1605, paris changed 0
*******the 1606 sample*******
L==H
fullset, iter:5 i:1606, paris changed 0
*******the 1607 sample*******
fullset, iter:5 i:1607, paris changed 0
*******the 1608 sample*******
j not moving enough
fullset, iter:5 i:1608, paris changed 0
*******the 1609 sample*******
L==H
fullset, iter:5 i:1609, paris changed 0
*******the 1610 sample*******
j not moving enough
fullset, iter:5 i:1610, paris changed 0
*******the 1611 sample*******
fullset, iter:5 i:1611, paris changed 0
*******the 1612 sample*******
fullset, iter:5 i:1612, paris changed 0
*******the 1613 sample*******
fullset, iter:5 i:1613, paris changed 0
*******the 1614 sample*******
fullset, iter:5 i:1614, p

L==H
fullset, iter:5 i:1719, paris changed 0
*******the 1720 sample*******
L==H
fullset, iter:5 i:1720, paris changed 0
*******the 1721 sample*******
fullset, iter:5 i:1721, paris changed 0
*******the 1722 sample*******
L==H
fullset, iter:5 i:1722, paris changed 0
*******the 1723 sample*******
L==H
fullset, iter:5 i:1723, paris changed 0
*******the 1724 sample*******
fullset, iter:5 i:1724, paris changed 0
*******the 1725 sample*******
fullset, iter:5 i:1725, paris changed 0
*******the 1726 sample*******
L==H
fullset, iter:5 i:1726, paris changed 0
*******the 1727 sample*******
fullset, iter:5 i:1727, paris changed 0
*******the 1728 sample*******
L==H
fullset, iter:5 i:1728, paris changed 0
*******the 1729 sample*******
L==H
fullset, iter:5 i:1729, paris changed 0
*******the 1730 sample*******
j not moving enough
fullset, iter:5 i:1730, paris changed 0
*******the 1731 sample*******
j not moving enough
fullset, iter:5 i:1731, paris changed 0
*******the 1732 sample*******
j not moving en

j not moving enough
fullset, iter:5 i:1818, paris changed 1
*******the 1819 sample*******
j not moving enough
fullset, iter:5 i:1819, paris changed 1
*******the 1820 sample*******
fullset, iter:5 i:1820, paris changed 1
*******the 1821 sample*******
j not moving enough
fullset, iter:5 i:1821, paris changed 1
*******the 1822 sample*******
j not moving enough
fullset, iter:5 i:1822, paris changed 1
*******the 1823 sample*******
j not moving enough
fullset, iter:5 i:1823, paris changed 1
*******the 1824 sample*******
j not moving enough
fullset, iter:5 i:1824, paris changed 1
*******the 1825 sample*******
j not moving enough
fullset, iter:5 i:1825, paris changed 1
*******the 1826 sample*******
j not moving enough
fullset, iter:5 i:1826, paris changed 1
*******the 1827 sample*******
j not moving enough
fullset, iter:5 i:1827, paris changed 1
*******the 1828 sample*******
j not moving enough
fullset, iter:5 i:1828, paris changed 1
*******the 1829 sample*******
j not moving enough
fullset, i

j not moving enough
fullset, iter:5 i:1919, paris changed 2
*******the 1920 sample*******
j not moving enough
fullset, iter:5 i:1920, paris changed 2
*******the 1921 sample*******
j not moving enough
fullset, iter:5 i:1921, paris changed 2
*******the 1922 sample*******
j not moving enough
fullset, iter:5 i:1922, paris changed 2
*******the 1923 sample*******
j not moving enough
fullset, iter:5 i:1923, paris changed 2
*******the 1924 sample*******
j not moving enough
fullset, iter:5 i:1924, paris changed 2
*******the 1925 sample*******
fullset, iter:5 i:1925, paris changed 2
*******the 1926 sample*******
j not moving enough
fullset, iter:5 i:1926, paris changed 2
*******the 1927 sample*******
j not moving enough
fullset, iter:5 i:1927, paris changed 2
*******the 1928 sample*******
fullset, iter:5 i:1928, paris changed 3
*******the 1929 sample*******
fullset, iter:5 i:1929, paris changed 3
*******the 1930 sample*******
j not moving enough
fullset, iter:5 i:1930, paris changed 3
*******the

j not moving enough
non-bound, iter:6 i:1108, paris changed 0
*******the 1110 sample*******
j not moving enough
non-bound, iter:6 i:1110, paris changed 0
*******the 1111 sample*******
j not moving enough
non-bound, iter:6 i:1111, paris changed 0
*******the 1112 sample*******
j not moving enough
non-bound, iter:6 i:1112, paris changed 0
*******the 1358 sample*******
j not moving enough
non-bound, iter:6 i:1358, paris changed 0
*******the 1372 sample*******
j not moving enough
non-bound, iter:6 i:1372, paris changed 0
*******the 1374 sample*******
j not moving enough
non-bound, iter:6 i:1374, paris changed 0
*******the 1390 sample*******
j not moving enough
non-bound, iter:6 i:1390, paris changed 0
*******the 1396 sample*******
j not moving enough
non-bound, iter:6 i:1396, paris changed 0
*******the 1437 sample*******
j not moving enough
non-bound, iter:6 i:1437, paris changed 0
*******the 1449 sample*******
j not moving enough
non-bound, iter:6 i:1449, paris changed 0
*******the 1481 sa

j not moving enough
non-bound, iter:6 i:1842, paris changed 0
*******the 1843 sample*******
j not moving enough
non-bound, iter:6 i:1843, paris changed 0
*******the 1844 sample*******
non-bound, iter:6 i:1844, paris changed 0
*******the 1845 sample*******
j not moving enough
non-bound, iter:6 i:1845, paris changed 0
*******the 1847 sample*******
j not moving enough
non-bound, iter:6 i:1847, paris changed 0
*******the 1848 sample*******
j not moving enough
non-bound, iter:6 i:1848, paris changed 0
*******the 1849 sample*******
j not moving enough
non-bound, iter:6 i:1849, paris changed 0
*******the 1850 sample*******
j not moving enough
non-bound, iter:6 i:1850, paris changed 0
*******the 1851 sample*******
j not moving enough
non-bound, iter:6 i:1851, paris changed 0
*******the 1853 sample*******
j not moving enough
non-bound, iter:6 i:1853, paris changed 0
*******the 1854 sample*******
j not moving enough
non-bound, iter:6 i:1854, paris changed 0
*******the 1856 sample*******
j not mo

j not moving enough
non-bound, iter:7 i:828, paris changed 0
*******the 831 sample*******
j not moving enough
non-bound, iter:7 i:831, paris changed 0
*******the 832 sample*******
j not moving enough
non-bound, iter:7 i:832, paris changed 0
*******the 834 sample*******
j not moving enough
non-bound, iter:7 i:834, paris changed 0
*******the 835 sample*******
j not moving enough
non-bound, iter:7 i:835, paris changed 0
*******the 852 sample*******
j not moving enough
non-bound, iter:7 i:852, paris changed 0
*******the 875 sample*******
j not moving enough
non-bound, iter:7 i:875, paris changed 0
*******the 879 sample*******
j not moving enough
non-bound, iter:7 i:879, paris changed 0
*******the 890 sample*******
j not moving enough
non-bound, iter:7 i:890, paris changed 0
*******the 901 sample*******
j not moving enough
non-bound, iter:7 i:901, paris changed 0
*******the 912 sample*******
j not moving enough
non-bound, iter:7 i:912, paris changed 0
*******the 920 sample*******
j not movi

*******the 1780 sample*******
j not moving enough
non-bound, iter:7 i:1780, paris changed 0
*******the 1781 sample*******
j not moving enough
non-bound, iter:7 i:1781, paris changed 0
*******the 1784 sample*******
j not moving enough
non-bound, iter:7 i:1784, paris changed 0
*******the 1785 sample*******
j not moving enough
non-bound, iter:7 i:1785, paris changed 0
*******the 1786 sample*******
j not moving enough
non-bound, iter:7 i:1786, paris changed 0
*******the 1787 sample*******
j not moving enough
non-bound, iter:7 i:1787, paris changed 0
*******the 1790 sample*******
j not moving enough
non-bound, iter:7 i:1790, paris changed 0
*******the 1791 sample*******
j not moving enough
non-bound, iter:7 i:1791, paris changed 0
*******the 1792 sample*******
j not moving enough
non-bound, iter:7 i:1792, paris changed 0
*******the 1794 sample*******
j not moving enough
non-bound, iter:7 i:1794, paris changed 0
*******the 1800 sample*******
j not moving enough
non-bound, iter:7 i:1800, pari

L==H
fullset, iter:8 i:30, paris changed 0
*******the 31 sample*******
fullset, iter:8 i:31, paris changed 0
*******the 32 sample*******
L==H
fullset, iter:8 i:32, paris changed 0
*******the 33 sample*******
fullset, iter:8 i:33, paris changed 0
*******the 34 sample*******
fullset, iter:8 i:34, paris changed 0
*******the 35 sample*******
fullset, iter:8 i:35, paris changed 0
*******the 36 sample*******
L==H
fullset, iter:8 i:36, paris changed 0
*******the 37 sample*******
L==H
fullset, iter:8 i:37, paris changed 0
*******the 38 sample*******
j not moving enough
fullset, iter:8 i:38, paris changed 0
*******the 39 sample*******
fullset, iter:8 i:39, paris changed 0
*******the 40 sample*******
L==H
fullset, iter:8 i:40, paris changed 0
*******the 41 sample*******
fullset, iter:8 i:41, paris changed 0
*******the 42 sample*******
fullset, iter:8 i:42, paris changed 0
*******the 43 sample*******
fullset, iter:8 i:43, paris changed 0
*******the 44 sample*******
fullset, iter:8 i:44, paris cha

j not moving enough
fullset, iter:8 i:165, paris changed 0
*******the 166 sample*******
fullset, iter:8 i:166, paris changed 0
*******the 167 sample*******
fullset, iter:8 i:167, paris changed 0
*******the 168 sample*******
fullset, iter:8 i:168, paris changed 0
*******the 169 sample*******
L==H
fullset, iter:8 i:169, paris changed 0
*******the 170 sample*******
fullset, iter:8 i:170, paris changed 0
*******the 171 sample*******
fullset, iter:8 i:171, paris changed 0
*******the 172 sample*******
fullset, iter:8 i:172, paris changed 0
*******the 173 sample*******
fullset, iter:8 i:173, paris changed 0
*******the 174 sample*******
fullset, iter:8 i:174, paris changed 0
*******the 175 sample*******
fullset, iter:8 i:175, paris changed 0
*******the 176 sample*******
fullset, iter:8 i:176, paris changed 0
*******the 177 sample*******
fullset, iter:8 i:177, paris changed 0
*******the 178 sample*******
fullset, iter:8 i:178, paris changed 0
*******the 179 sample*******
fullset, iter:8 i:179, 

L==H
fullset, iter:8 i:304, paris changed 0
*******the 305 sample*******
fullset, iter:8 i:305, paris changed 0
*******the 306 sample*******
j not moving enough
fullset, iter:8 i:306, paris changed 0
*******the 307 sample*******
fullset, iter:8 i:307, paris changed 0
*******the 308 sample*******
fullset, iter:8 i:308, paris changed 0
*******the 309 sample*******
j not moving enough
fullset, iter:8 i:309, paris changed 0
*******the 310 sample*******
fullset, iter:8 i:310, paris changed 0
*******the 311 sample*******
fullset, iter:8 i:311, paris changed 0
*******the 312 sample*******
fullset, iter:8 i:312, paris changed 0
*******the 313 sample*******
L==H
fullset, iter:8 i:313, paris changed 0
*******the 314 sample*******
j not moving enough
fullset, iter:8 i:314, paris changed 0
*******the 315 sample*******
fullset, iter:8 i:315, paris changed 0
*******the 316 sample*******
j not moving enough
fullset, iter:8 i:316, paris changed 0
*******the 317 sample*******
fullset, iter:8 i:317, par

j not moving enough
fullset, iter:8 i:424, paris changed 0
*******the 425 sample*******
fullset, iter:8 i:425, paris changed 0
*******the 426 sample*******
fullset, iter:8 i:426, paris changed 0
*******the 427 sample*******
fullset, iter:8 i:427, paris changed 0
*******the 428 sample*******
fullset, iter:8 i:428, paris changed 0
*******the 429 sample*******
fullset, iter:8 i:429, paris changed 0
*******the 430 sample*******
fullset, iter:8 i:430, paris changed 0
*******the 431 sample*******
fullset, iter:8 i:431, paris changed 0
*******the 432 sample*******
fullset, iter:8 i:432, paris changed 0
*******the 433 sample*******
fullset, iter:8 i:433, paris changed 0
*******the 434 sample*******
fullset, iter:8 i:434, paris changed 0
*******the 435 sample*******
fullset, iter:8 i:435, paris changed 0
*******the 436 sample*******
fullset, iter:8 i:436, paris changed 0
*******the 437 sample*******
fullset, iter:8 i:437, paris changed 0
*******the 438 sample*******
L==H
fullset, iter:8 i:438, 

j not moving enough
fullset, iter:8 i:551, paris changed 0
*******the 552 sample*******
fullset, iter:8 i:552, paris changed 0
*******the 553 sample*******
fullset, iter:8 i:553, paris changed 0
*******the 554 sample*******
fullset, iter:8 i:554, paris changed 0
*******the 555 sample*******
fullset, iter:8 i:555, paris changed 0
*******the 556 sample*******
fullset, iter:8 i:556, paris changed 0
*******the 557 sample*******
fullset, iter:8 i:557, paris changed 0
*******the 558 sample*******
fullset, iter:8 i:558, paris changed 0
*******the 559 sample*******
fullset, iter:8 i:559, paris changed 0
*******the 560 sample*******
fullset, iter:8 i:560, paris changed 0
*******the 561 sample*******
fullset, iter:8 i:561, paris changed 0
*******the 562 sample*******
fullset, iter:8 i:562, paris changed 0
*******the 563 sample*******
fullset, iter:8 i:563, paris changed 0
*******the 564 sample*******
fullset, iter:8 i:564, paris changed 0
*******the 565 sample*******
fullset, iter:8 i:565, paris

L==H
fullset, iter:8 i:685, paris changed 0
*******the 686 sample*******
fullset, iter:8 i:686, paris changed 0
*******the 687 sample*******
fullset, iter:8 i:687, paris changed 0
*******the 688 sample*******
fullset, iter:8 i:688, paris changed 0
*******the 689 sample*******
fullset, iter:8 i:689, paris changed 0
*******the 690 sample*******
fullset, iter:8 i:690, paris changed 0
*******the 691 sample*******
j not moving enough
fullset, iter:8 i:691, paris changed 0
*******the 692 sample*******
fullset, iter:8 i:692, paris changed 0
*******the 693 sample*******
L==H
fullset, iter:8 i:693, paris changed 0
*******the 694 sample*******
fullset, iter:8 i:694, paris changed 0
*******the 695 sample*******
fullset, iter:8 i:695, paris changed 0
*******the 696 sample*******
fullset, iter:8 i:696, paris changed 0
*******the 697 sample*******
L==H
fullset, iter:8 i:697, paris changed 0
*******the 698 sample*******
fullset, iter:8 i:698, paris changed 0
*******the 699 sample*******
fullset, iter

j not moving enough
fullset, iter:8 i:822, paris changed 0
*******the 823 sample*******
L==H
fullset, iter:8 i:823, paris changed 0
*******the 824 sample*******
fullset, iter:8 i:824, paris changed 0
*******the 825 sample*******
fullset, iter:8 i:825, paris changed 0
*******the 826 sample*******
fullset, iter:8 i:826, paris changed 0
*******the 827 sample*******
L==H
fullset, iter:8 i:827, paris changed 0
*******the 828 sample*******
j not moving enough
fullset, iter:8 i:828, paris changed 0
*******the 829 sample*******
fullset, iter:8 i:829, paris changed 0
*******the 830 sample*******
fullset, iter:8 i:830, paris changed 0
*******the 831 sample*******
j not moving enough
fullset, iter:8 i:831, paris changed 0
*******the 832 sample*******
j not moving enough
fullset, iter:8 i:832, paris changed 0
*******the 833 sample*******
L==H
fullset, iter:8 i:833, paris changed 0
*******the 834 sample*******
j not moving enough
fullset, iter:8 i:834, paris changed 0
*******the 835 sample*******
j

j not moving enough
fullset, iter:8 i:961, paris changed 0
*******the 962 sample*******
fullset, iter:8 i:962, paris changed 0
*******the 963 sample*******
L==H
fullset, iter:8 i:963, paris changed 0
*******the 964 sample*******
fullset, iter:8 i:964, paris changed 0
*******the 965 sample*******
fullset, iter:8 i:965, paris changed 0
*******the 966 sample*******
fullset, iter:8 i:966, paris changed 0
*******the 967 sample*******
j not moving enough
fullset, iter:8 i:967, paris changed 0
*******the 968 sample*******
j not moving enough
fullset, iter:8 i:968, paris changed 0
*******the 969 sample*******
fullset, iter:8 i:969, paris changed 0
*******the 970 sample*******
fullset, iter:8 i:970, paris changed 0
*******the 971 sample*******
fullset, iter:8 i:971, paris changed 0
*******the 972 sample*******
fullset, iter:8 i:972, paris changed 0
*******the 973 sample*******
fullset, iter:8 i:973, paris changed 0
*******the 974 sample*******
fullset, iter:8 i:974, paris changed 0
*******the 9

j not moving enough
fullset, iter:8 i:1086, paris changed 0
*******the 1087 sample*******
j not moving enough
fullset, iter:8 i:1087, paris changed 0
*******the 1088 sample*******
L==H
fullset, iter:8 i:1088, paris changed 0
*******the 1089 sample*******
L==H
fullset, iter:8 i:1089, paris changed 0
*******the 1090 sample*******
L==H
fullset, iter:8 i:1090, paris changed 0
*******the 1091 sample*******
fullset, iter:8 i:1091, paris changed 0
*******the 1092 sample*******
fullset, iter:8 i:1092, paris changed 0
*******the 1093 sample*******
fullset, iter:8 i:1093, paris changed 0
*******the 1094 sample*******
fullset, iter:8 i:1094, paris changed 0
*******the 1095 sample*******
fullset, iter:8 i:1095, paris changed 0
*******the 1096 sample*******
L==H
fullset, iter:8 i:1096, paris changed 0
*******the 1097 sample*******
L==H
fullset, iter:8 i:1097, paris changed 0
*******the 1098 sample*******
L==H
fullset, iter:8 i:1098, paris changed 0
*******the 1099 sample*******
L==H
fullset, iter:8

fullset, iter:8 i:1271, paris changed 0
*******the 1272 sample*******
fullset, iter:8 i:1272, paris changed 0
*******the 1273 sample*******
fullset, iter:8 i:1273, paris changed 0
*******the 1274 sample*******
fullset, iter:8 i:1274, paris changed 0
*******the 1275 sample*******
fullset, iter:8 i:1275, paris changed 0
*******the 1276 sample*******
fullset, iter:8 i:1276, paris changed 0
*******the 1277 sample*******
fullset, iter:8 i:1277, paris changed 0
*******the 1278 sample*******
fullset, iter:8 i:1278, paris changed 0
*******the 1279 sample*******
fullset, iter:8 i:1279, paris changed 0
*******the 1280 sample*******
fullset, iter:8 i:1280, paris changed 0
*******the 1281 sample*******
fullset, iter:8 i:1281, paris changed 0
*******the 1282 sample*******
fullset, iter:8 i:1282, paris changed 0
*******the 1283 sample*******
fullset, iter:8 i:1283, paris changed 0
*******the 1284 sample*******
fullset, iter:8 i:1284, paris changed 0
*******the 1285 sample*******
fullset, iter:8 i:12

j not moving enough
fullset, iter:8 i:1390, paris changed 0
*******the 1391 sample*******
L==H
fullset, iter:8 i:1391, paris changed 0
*******the 1392 sample*******
fullset, iter:8 i:1392, paris changed 0
*******the 1393 sample*******
fullset, iter:8 i:1393, paris changed 0
*******the 1394 sample*******
fullset, iter:8 i:1394, paris changed 0
*******the 1395 sample*******
fullset, iter:8 i:1395, paris changed 0
*******the 1396 sample*******
j not moving enough
fullset, iter:8 i:1396, paris changed 0
*******the 1397 sample*******
fullset, iter:8 i:1397, paris changed 0
*******the 1398 sample*******
fullset, iter:8 i:1398, paris changed 0
*******the 1399 sample*******
fullset, iter:8 i:1399, paris changed 0
*******the 1400 sample*******
fullset, iter:8 i:1400, paris changed 0
*******the 1401 sample*******
fullset, iter:8 i:1401, paris changed 0
*******the 1402 sample*******
fullset, iter:8 i:1402, paris changed 0
*******the 1403 sample*******
fullset, iter:8 i:1403, paris changed 0
*****

j not moving enough
fullset, iter:8 i:1538, paris changed 0
*******the 1539 sample*******
fullset, iter:8 i:1539, paris changed 0
*******the 1540 sample*******
j not moving enough
fullset, iter:8 i:1540, paris changed 0
*******the 1541 sample*******
fullset, iter:8 i:1541, paris changed 0
*******the 1542 sample*******
L==H
fullset, iter:8 i:1542, paris changed 0
*******the 1543 sample*******
fullset, iter:8 i:1543, paris changed 0
*******the 1544 sample*******
fullset, iter:8 i:1544, paris changed 0
*******the 1545 sample*******
fullset, iter:8 i:1545, paris changed 0
*******the 1546 sample*******
fullset, iter:8 i:1546, paris changed 0
*******the 1547 sample*******
fullset, iter:8 i:1547, paris changed 0
*******the 1548 sample*******
fullset, iter:8 i:1548, paris changed 0
*******the 1549 sample*******
fullset, iter:8 i:1549, paris changed 0
*******the 1550 sample*******
fullset, iter:8 i:1550, paris changed 0
*******the 1551 sample*******
j not moving enough
fullset, iter:8 i:1551, p

L==H
fullset, iter:8 i:1661, paris changed 0
*******the 1662 sample*******
fullset, iter:8 i:1662, paris changed 0
*******the 1663 sample*******
j not moving enough
fullset, iter:8 i:1663, paris changed 0
*******the 1664 sample*******
fullset, iter:8 i:1664, paris changed 0
*******the 1665 sample*******
L==H
fullset, iter:8 i:1665, paris changed 0
*******the 1666 sample*******
L==H
fullset, iter:8 i:1666, paris changed 0
*******the 1667 sample*******
L==H
fullset, iter:8 i:1667, paris changed 0
*******the 1668 sample*******
fullset, iter:8 i:1668, paris changed 0
*******the 1669 sample*******
L==H
fullset, iter:8 i:1669, paris changed 0
*******the 1670 sample*******
L==H
fullset, iter:8 i:1670, paris changed 0
*******the 1671 sample*******
fullset, iter:8 i:1671, paris changed 0
*******the 1672 sample*******
L==H
fullset, iter:8 i:1672, paris changed 0
*******the 1673 sample*******
L==H
fullset, iter:8 i:1673, paris changed 0
*******the 1674 sample*******
fullset, iter:8 i:1674, paris 

fullset, iter:8 i:1767, paris changed 0
*******the 1768 sample*******
j not moving enough
fullset, iter:8 i:1768, paris changed 0
*******the 1769 sample*******
j not moving enough
fullset, iter:8 i:1769, paris changed 0
*******the 1770 sample*******
j not moving enough
fullset, iter:8 i:1770, paris changed 0
*******the 1771 sample*******
j not moving enough
fullset, iter:8 i:1771, paris changed 0
*******the 1772 sample*******
j not moving enough
fullset, iter:8 i:1772, paris changed 0
*******the 1773 sample*******
j not moving enough
fullset, iter:8 i:1773, paris changed 0
*******the 1774 sample*******
j not moving enough
fullset, iter:8 i:1774, paris changed 0
*******the 1775 sample*******
j not moving enough
fullset, iter:8 i:1775, paris changed 0
*******the 1776 sample*******
j not moving enough
fullset, iter:8 i:1776, paris changed 0
*******the 1777 sample*******
j not moving enough
fullset, iter:8 i:1777, paris changed 0
*******the 1778 sample*******
j not moving enough
fullset, i

j not moving enough
fullset, iter:8 i:1862, paris changed 0
*******the 1863 sample*******
j not moving enough
fullset, iter:8 i:1863, paris changed 0
*******the 1864 sample*******
j not moving enough
fullset, iter:8 i:1864, paris changed 0
*******the 1865 sample*******
j not moving enough
fullset, iter:8 i:1865, paris changed 0
*******the 1866 sample*******
j not moving enough
fullset, iter:8 i:1866, paris changed 0
*******the 1867 sample*******
j not moving enough
fullset, iter:8 i:1867, paris changed 0
*******the 1868 sample*******
j not moving enough
fullset, iter:8 i:1868, paris changed 0
*******the 1869 sample*******
j not moving enough
fullset, iter:8 i:1869, paris changed 0
*******the 1870 sample*******
fullset, iter:8 i:1870, paris changed 0
*******the 1871 sample*******
j not moving enough
fullset, iter:8 i:1871, paris changed 0
*******the 1872 sample*******
j not moving enough
fullset, iter:8 i:1872, paris changed 0
*******the 1873 sample*******
j not moving enough
fullset, i

[matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[ 1.]]),
 matrix([[

In [2]:
clf2 = svm.svm_mlia()
data2, labels2 = svm.load_dataset('testSet_svm.txt')
os2 = clf2.smoP(data2, labels2, 0.6, 0.001, 40, ('lin',1.3))

*******the 0 sample*******
L==H
fullset, iter:0 i:0, paris changed 0
*******the 1 sample*******
L==H
fullset, iter:0 i:1, paris changed 0
*******the 2 sample*******
fullset, iter:0 i:2, paris changed 1
*******the 3 sample*******
L==H
fullset, iter:0 i:3, paris changed 1
*******the 4 sample*******
fullset, iter:0 i:4, paris changed 2
*******the 5 sample*******
fullset, iter:0 i:5, paris changed 2
*******the 6 sample*******
fullset, iter:0 i:6, paris changed 2
*******the 7 sample*******
j not moving enough
fullset, iter:0 i:7, paris changed 2
*******the 8 sample*******
L==H
fullset, iter:0 i:8, paris changed 2
*******the 9 sample*******
fullset, iter:0 i:9, paris changed 2
*******the 10 sample*******
L==H
fullset, iter:0 i:10, paris changed 2
*******the 11 sample*******
L==H
fullset, iter:0 i:11, paris changed 2
*******the 12 sample*******
L==H
fullset, iter:0 i:12, paris changed 2
*******the 13 sample*******
fullset, iter:0 i:13, paris changed 2
*******the 14 sample*******
L==H
fullset,

In [6]:
clf2.pred(os2,data2[2])

matrix([[ 1.]])

In [4]:
clf1 = svm.svm_mlia()
data1, labels1 = svm.load_dataset('testSetRBF.txt')
clf1.smoP(data1, labels1, 200, 0.001, 1000, ('rbf',1.3))

*******the 0 sample*******
fullset, iter:0 i:0, paris changed 1
*******the 1 sample*******
fullset, iter:0 i:1, paris changed 2
*******the 2 sample*******
fullset, iter:0 i:2, paris changed 3
*******the 3 sample*******
fullset, iter:0 i:3, paris changed 4
*******the 4 sample*******
fullset, iter:0 i:4, paris changed 4
*******the 5 sample*******
fullset, iter:0 i:5, paris changed 5
*******the 6 sample*******
fullset, iter:0 i:6, paris changed 5
*******the 7 sample*******
fullset, iter:0 i:7, paris changed 5
*******the 8 sample*******
fullset, iter:0 i:8, paris changed 6
*******the 9 sample*******
fullset, iter:0 i:9, paris changed 6
*******the 10 sample*******
fullset, iter:0 i:10, paris changed 7
*******the 11 sample*******
fullset, iter:0 i:11, paris changed 8
*******the 12 sample*******
fullset, iter:0 i:12, paris changed 8
*******the 13 sample*******
fullset, iter:0 i:13, paris changed 9
*******the 14 sample*******
fullset, iter:0 i:14, paris changed 10
*******the 15 sample*******
f

j not moving enough
non-bound, iter:3 i:29, paris changed 1
*******the 31 sample*******
j not moving enough
non-bound, iter:3 i:31, paris changed 1
*******the 33 sample*******
j not moving enough
non-bound, iter:3 i:33, paris changed 1
*******the 36 sample*******
j not moving enough
non-bound, iter:3 i:36, paris changed 1
*******the 40 sample*******
j not moving enough
non-bound, iter:3 i:40, paris changed 1
*******the 41 sample*******
j not moving enough
non-bound, iter:3 i:41, paris changed 1
*******the 42 sample*******
j not moving enough
non-bound, iter:3 i:42, paris changed 1
*******the 45 sample*******
j not moving enough
non-bound, iter:3 i:45, paris changed 1
*******the 50 sample*******
j not moving enough
non-bound, iter:3 i:50, paris changed 1
*******the 52 sample*******
j not moving enough
non-bound, iter:3 i:52, paris changed 1
*******the 54 sample*******
j not moving enough
non-bound, iter:3 i:54, paris changed 1
*******the 58 sample*******
j not moving enough
non-bound, i

In [5]:
result_valid = clf1.pred(data1, labels1)
data3, labels3 = svm.load_dataset('testSetRBF2.txt')
result_test = clf1.pred(data3, labels3)

error rate: 0.02
error rate: 0.03


In [13]:
len(result_test)

100

In [14]:
len(result_valid)

100

In [4]:
b

matrix([[-10.51834798]])

In [20]:
data

[[-0.214824, 0.662756],
 [-0.061569, -0.091875],
 [0.406933, 0.648055],
 [0.22365, 0.130142],
 [0.231317, 0.766906],
 [-0.7488, -0.531637],
 [-0.557789, 0.375797],
 [0.207123, -0.019463],
 [0.286462, 0.71947],
 [0.1953, -0.179039],
 [-0.152696, -0.15303],
 [0.384471, 0.653336],
 [-0.11728, -0.153217],
 [-0.238076, 0.000583],
 [-0.413576, 0.145681],
 [0.490767, -0.680029],
 [0.199894, -0.199381],
 [-0.356048, 0.53796],
 [-0.392868, -0.125261],
 [0.353588, -0.070617],
 [0.020984, 0.92572],
 [-0.475167, -0.346247],
 [0.074952, 0.042783],
 [0.394164, -0.058217],
 [0.663418, 0.436525],
 [0.402158, 0.577744],
 [-0.449349, -0.038074],
 [0.61908, -0.088188],
 [0.268066, -0.071621],
 [-0.015165, 0.359326],
 [0.539368, -0.374972],
 [-0.319153, 0.629673],
 [0.694424, 0.64118],
 [0.079522, 0.193198],
 [0.253289, -0.285861],
 [-0.035558, -0.010086],
 [-0.403483, 0.474466],
 [-0.034312, 0.995685],
 [-0.590657, 0.438051],
 [-0.098871, -0.023953],
 [-0.250001, 0.141621],
 [-0.012998, 0.525985],
 [0.15

In [124]:
np.multiply(np.mat([2]),np.ones((1,2)))

matrix([[ 2.,  2.]])

In [34]:
alphas

matrix([[  2.88776647],
        [  6.21487525],
        [  0.        ],
        [  2.70892161],
        [  0.        ],
        [  0.        ],
        [  0.        ],
        [  0.09528397],
        [  0.        ],
        [  0.        ],
        [  4.39547498],
        [  0.        ],
        [  4.27540358],
        [  4.06245552],
        [ 17.54072512],
        [  0.        ],
        [  9.13042201],
        [ 18.24955858],
        [  0.        ],
        [  0.        ],
        [  0.        ],
        [ 79.37160117],
        [  6.70841041],
        [ 17.74934105],
        [  0.        ],
        [  0.        ],
        [ 44.402655  ],
        [ 12.06846651],
        [  9.60697413],
        [ 13.41879156],
        [  0.        ],
        [  3.5980746 ],
        [  0.        ],
        [  0.        ],
        [  0.        ],
        [  0.        ],
        [ 15.47501401],
        [  0.        ],
        [  0.        ],
        [  0.        ],
        [ 10.43593908],
        [ 16.705

In [35]:
b

matrix([[-10.69739373]])

In [89]:
x = np.mat([[1,2],[0,4],[5,6]])

In [65]:
np.nonzero(x[:,0].A)[0]

array([0, 2])

In [105]:
np.multiply(np.mat([2]),np.mat([1,2]))

matrix([[2, 4]])

In [71]:
x[:,0].A

array([[1],
       [0],
       [5]])

In [76]:
np.nonzero(x[:,0].A)[0][0]

0

In [73]:
np.nonzero(x[:,0].A)

(array([0, 2]), array([0, 0]))

In [13]:
import numpy as np
import svm_mlia as svm
import importlib
import matplotlib
import matplotlib.pyplot as plt
importlib.reload(svm)

clf = svm.svm_mlia()
data, labels = clf.load_dataset('testSet_svm.txt')
b, alphas = clf.smo_simple(data, labels, 0.6, 0.001, 40)

**************iteration 0 start**************
*******the 0 sample*******
L==H
*******the 1 sample*******
L==H
*******the 2 sample*******
L==H
*******the 3 sample*******
L==H
*******the 4 sample*******
iter: 0 i:4 j:89, pairs changed 1
*******the 5 sample*******
L==H
*******the 6 sample*******
*******the 7 sample*******
iter: 0 i:7 j:5, pairs changed 2
*******the 8 sample*******
L==H
*******the 9 sample*******
*******the 10 sample*******
j not moving enough
*******the 11 sample*******
*******the 12 sample*******
*******the 13 sample*******
iter: 0 i:13 j:56, pairs changed 3
*******the 14 sample*******
*******the 15 sample*******
*******the 16 sample*******
*******the 17 sample*******
L==H
*******the 18 sample*******
*******the 19 sample*******
*******the 20 sample*******
*******the 21 sample*******
*******the 22 sample*******
*******the 23 sample*******
L==H
*******the 24 sample*******
L==H
*******the 25 sample*******
*******the 26 sample*******
*******the 27 sample*******
*******the 28

*******the 43 sample*******
*******the 44 sample*******
*******the 45 sample*******
j not moving enough
*******the 46 sample*******
j not moving enough
*******the 47 sample*******
j not moving enough
*******the 48 sample*******
*******the 49 sample*******
*******the 50 sample*******
*******the 51 sample*******
j not moving enough
*******the 52 sample*******
*******the 53 sample*******
*******the 54 sample*******
L==H
*******the 55 sample*******
iter: 0 i:55 j:23, pairs changed 4
*******the 56 sample*******
iter: 0 i:56 j:52, pairs changed 5
*******the 57 sample*******
*******the 58 sample*******
*******the 59 sample*******
*******the 60 sample*******
*******the 61 sample*******
*******the 62 sample*******
*******the 63 sample*******
*******the 64 sample*******
*******the 65 sample*******
*******the 66 sample*******
*******the 67 sample*******
*******the 68 sample*******
*******the 69 sample*******
j not moving enough
*******the 70 sample*******
*******the 71 sample*******
j not moving 

*******the 52 sample*******
j not moving enough
*******the 53 sample*******
*******the 54 sample*******
j not moving enough
*******the 55 sample*******
j not moving enough
*******the 56 sample*******
*******the 57 sample*******
j not moving enough
*******the 58 sample*******
*******the 59 sample*******
*******the 60 sample*******
*******the 61 sample*******
*******the 62 sample*******
*******the 63 sample*******
*******the 64 sample*******
*******the 65 sample*******
*******the 66 sample*******
*******the 67 sample*******
*******the 68 sample*******
*******the 69 sample*******
j not moving enough
*******the 70 sample*******
*******the 71 sample*******
*******the 72 sample*******
*******the 73 sample*******
*******the 74 sample*******
*******the 75 sample*******
*******the 76 sample*******
*******the 77 sample*******
*******the 78 sample*******
*******the 79 sample*******
*******the 80 sample*******
*******the 81 sample*******
*******the 82 sample*******
*******the 83 sample*******
****

*******the 48 sample*******
*******the 49 sample*******
*******the 50 sample*******
*******the 51 sample*******
*******the 52 sample*******
j not moving enough
*******the 53 sample*******
*******the 54 sample*******
iter: 2 i:54 j:29, pairs changed 1
*******the 55 sample*******
j not moving enough
*******the 56 sample*******
*******the 57 sample*******
*******the 58 sample*******
*******the 59 sample*******
*******the 60 sample*******
*******the 61 sample*******
*******the 62 sample*******
*******the 63 sample*******
*******the 64 sample*******
*******the 65 sample*******
*******the 66 sample*******
*******the 67 sample*******
*******the 68 sample*******
*******the 69 sample*******
j not moving enough
*******the 70 sample*******
*******the 71 sample*******
*******the 72 sample*******
*******the 73 sample*******
*******the 74 sample*******
*******the 75 sample*******
*******the 76 sample*******
*******the 77 sample*******
*******the 78 sample*******
*******the 79 sample*******
*******th

*******the 98 sample*******
*******the 99 sample*******
iteration number: 4
**************iteration 4 start**************
*******the 0 sample*******
*******the 1 sample*******
*******the 2 sample*******
*******the 3 sample*******
*******the 4 sample*******
*******the 5 sample*******
*******the 6 sample*******
*******the 7 sample*******
*******the 8 sample*******
*******the 9 sample*******
*******the 10 sample*******
*******the 11 sample*******
*******the 12 sample*******
*******the 13 sample*******
*******the 14 sample*******
*******the 15 sample*******
*******the 16 sample*******
*******the 17 sample*******
j not moving enough
*******the 18 sample*******
*******the 19 sample*******
*******the 20 sample*******
*******the 21 sample*******
*******the 22 sample*******
*******the 23 sample*******
*******the 24 sample*******
*******the 25 sample*******
*******the 26 sample*******
*******the 27 sample*******
*******the 28 sample*******
*******the 29 sample*******
j not moving enough
*******t

*******the 71 sample*******
*******the 72 sample*******
*******the 73 sample*******
*******the 74 sample*******
*******the 75 sample*******
*******the 76 sample*******
*******the 77 sample*******
*******the 78 sample*******
*******the 79 sample*******
*******the 80 sample*******
*******the 81 sample*******
*******the 82 sample*******
*******the 83 sample*******
*******the 84 sample*******
*******the 85 sample*******
*******the 86 sample*******
*******the 87 sample*******
*******the 88 sample*******
*******the 89 sample*******
*******the 90 sample*******
*******the 91 sample*******
*******the 92 sample*******
*******the 93 sample*******
*******the 94 sample*******
*******the 95 sample*******
*******the 96 sample*******
*******the 97 sample*******
*******the 98 sample*******
*******the 99 sample*******
iteration number: 13
**************iteration 13 start**************
*******the 0 sample*******
*******the 1 sample*******
*******the 2 sample*******
*******the 3 sample*******
*******the 4

*******the 42 sample*******
*******the 43 sample*******
*******the 44 sample*******
*******the 45 sample*******
*******the 46 sample*******
*******the 47 sample*******
*******the 48 sample*******
*******the 49 sample*******
*******the 50 sample*******
*******the 51 sample*******
*******the 52 sample*******
j not moving enough
*******the 53 sample*******
*******the 54 sample*******
j not moving enough
*******the 55 sample*******
j not moving enough
*******the 56 sample*******
*******the 57 sample*******
*******the 58 sample*******
*******the 59 sample*******
*******the 60 sample*******
*******the 61 sample*******
*******the 62 sample*******
*******the 63 sample*******
*******the 64 sample*******
*******the 65 sample*******
*******the 66 sample*******
*******the 67 sample*******
*******the 68 sample*******
*******the 69 sample*******
*******the 70 sample*******
*******the 71 sample*******
*******the 72 sample*******
*******the 73 sample*******
*******the 74 sample*******
*******the 75 sa

*******the 74 sample*******
*******the 75 sample*******
*******the 76 sample*******
*******the 77 sample*******
*******the 78 sample*******
*******the 79 sample*******
*******the 80 sample*******
*******the 81 sample*******
*******the 82 sample*******
*******the 83 sample*******
*******the 84 sample*******
*******the 85 sample*******
*******the 86 sample*******
*******the 87 sample*******
*******the 88 sample*******
*******the 89 sample*******
*******the 90 sample*******
*******the 91 sample*******
*******the 92 sample*******
*******the 93 sample*******
*******the 94 sample*******
*******the 95 sample*******
*******the 96 sample*******
*******the 97 sample*******
*******the 98 sample*******
*******the 99 sample*******
iteration number: 9
**************iteration 9 start**************
*******the 0 sample*******
*******the 1 sample*******
*******the 2 sample*******
*******the 3 sample*******
*******the 4 sample*******
*******the 5 sample*******
*******the 6 sample*******
*******the 7 samp

*******the 49 sample*******
*******the 50 sample*******
*******the 51 sample*******
*******the 52 sample*******
*******the 53 sample*******
*******the 54 sample*******
*******the 55 sample*******
*******the 56 sample*******
*******the 57 sample*******
*******the 58 sample*******
*******the 59 sample*******
*******the 60 sample*******
*******the 61 sample*******
*******the 62 sample*******
*******the 63 sample*******
*******the 64 sample*******
*******the 65 sample*******
*******the 66 sample*******
*******the 67 sample*******
*******the 68 sample*******
*******the 69 sample*******
*******the 70 sample*******
*******the 71 sample*******
*******the 72 sample*******
*******the 73 sample*******
*******the 74 sample*******
*******the 75 sample*******
*******the 76 sample*******
*******the 77 sample*******
*******the 78 sample*******
*******the 79 sample*******
*******the 80 sample*******
*******the 81 sample*******
*******the 82 sample*******
*******the 83 sample*******
*******the 84 sample

*******the 9 sample*******
*******the 10 sample*******
*******the 11 sample*******
*******the 12 sample*******
*******the 13 sample*******
*******the 14 sample*******
*******the 15 sample*******
*******the 16 sample*******
*******the 17 sample*******
j not moving enough
*******the 18 sample*******
*******the 19 sample*******
*******the 20 sample*******
*******the 21 sample*******
*******the 22 sample*******
*******the 23 sample*******
j not moving enough
*******the 24 sample*******
*******the 25 sample*******
*******the 26 sample*******
*******the 27 sample*******
*******the 28 sample*******
*******the 29 sample*******
j not moving enough
*******the 30 sample*******
*******the 31 sample*******
*******the 32 sample*******
*******the 33 sample*******
*******the 34 sample*******
*******the 35 sample*******
*******the 36 sample*******
*******the 37 sample*******
*******the 38 sample*******
*******the 39 sample*******
*******the 40 sample*******
*******the 41 sample*******
*******the 42 sam

*******the 44 sample*******
*******the 45 sample*******
*******the 46 sample*******
*******the 47 sample*******
*******the 48 sample*******
*******the 49 sample*******
*******the 50 sample*******
*******the 51 sample*******
*******the 52 sample*******
j not moving enough
*******the 53 sample*******
*******the 54 sample*******
*******the 55 sample*******
j not moving enough
*******the 56 sample*******
*******the 57 sample*******
*******the 58 sample*******
*******the 59 sample*******
*******the 60 sample*******
*******the 61 sample*******
*******the 62 sample*******
*******the 63 sample*******
*******the 64 sample*******
*******the 65 sample*******
*******the 66 sample*******
*******the 67 sample*******
*******the 68 sample*******
*******the 69 sample*******
*******the 70 sample*******
*******the 71 sample*******
*******the 72 sample*******
*******the 73 sample*******
*******the 74 sample*******
*******the 75 sample*******
*******the 76 sample*******
*******the 77 sample*******
*******t

*******the 81 sample*******
*******the 82 sample*******
*******the 83 sample*******
*******the 84 sample*******
*******the 85 sample*******
*******the 86 sample*******
*******the 87 sample*******
*******the 88 sample*******
*******the 89 sample*******
*******the 90 sample*******
*******the 91 sample*******
*******the 92 sample*******
*******the 93 sample*******
*******the 94 sample*******
*******the 95 sample*******
*******the 96 sample*******
*******the 97 sample*******
*******the 98 sample*******
*******the 99 sample*******
iteration number: 3
**************iteration 3 start**************
*******the 0 sample*******
*******the 1 sample*******
*******the 2 sample*******
*******the 3 sample*******
*******the 4 sample*******
*******the 5 sample*******
*******the 6 sample*******
*******the 7 sample*******
*******the 8 sample*******
*******the 9 sample*******
*******the 10 sample*******
*******the 11 sample*******
*******the 12 sample*******
*******the 13 sample*******
*******the 14 sample

*******the 58 sample*******
*******the 59 sample*******
*******the 60 sample*******
*******the 61 sample*******
*******the 62 sample*******
*******the 63 sample*******
*******the 64 sample*******
*******the 65 sample*******
*******the 66 sample*******
*******the 67 sample*******
*******the 68 sample*******
*******the 69 sample*******
*******the 70 sample*******
*******the 71 sample*******
*******the 72 sample*******
*******the 73 sample*******
*******the 74 sample*******
*******the 75 sample*******
*******the 76 sample*******
*******the 77 sample*******
*******the 78 sample*******
*******the 79 sample*******
*******the 80 sample*******
*******the 81 sample*******
*******the 82 sample*******
*******the 83 sample*******
*******the 84 sample*******
*******the 85 sample*******
*******the 86 sample*******
*******the 87 sample*******
*******the 88 sample*******
*******the 89 sample*******
*******the 90 sample*******
*******the 91 sample*******
*******the 92 sample*******
*******the 93 sample

*******the 59 sample*******
*******the 60 sample*******
*******the 61 sample*******
*******the 62 sample*******
*******the 63 sample*******
*******the 64 sample*******
*******the 65 sample*******
*******the 66 sample*******
*******the 67 sample*******
*******the 68 sample*******
*******the 69 sample*******
*******the 70 sample*******
*******the 71 sample*******
*******the 72 sample*******
*******the 73 sample*******
*******the 74 sample*******
*******the 75 sample*******
*******the 76 sample*******
*******the 77 sample*******
*******the 78 sample*******
*******the 79 sample*******
*******the 80 sample*******
*******the 81 sample*******
*******the 82 sample*******
*******the 83 sample*******
*******the 84 sample*******
*******the 85 sample*******
*******the 86 sample*******
*******the 87 sample*******
*******the 88 sample*******
*******the 89 sample*******
*******the 90 sample*******
*******the 91 sample*******
*******the 92 sample*******
*******the 93 sample*******
*******the 94 sample

In [14]:
b

matrix([[-3.66381468]])

In [15]:
alphas[alphas>0]

matrix([[ 0.09597256,  0.21226948,  0.036597  ,  0.05800947,  0.28682958]])

In [ ]:
data[1,]

In [70]:
np.mat(data)[1]

matrix([[-1.395634,  4.662541]])

In [71]:
np.mat(data)[1,:]

matrix([[-1.395634,  4.662541]])

In [60]:
import numpy as np
import Bayes
import importlib
import matplotlib
import matplotlib.pyplot as plt
importlib.reload(Bayes)

#group = np.array([[1.0,1.1],[1.0,1.0],[0,0],[0,0.1]])
#labels = ['A','A','B','B']

clf = Bayes.Bayes()
data, labels = clf.load_dataset()
train = []
vocab_list = clf.create_vocab_list(data)
for s in data:
    train.append(clf.words2vec(vocab_list, s))
'''
clf = Bayes.Bayes()
clf.spam_test()
'''

'\nclf = Bayes.Bayes()\nclf.spam_test()\n'

In [58]:
a = np.mat([1,2,3])

In [60]:
a*a.T

matrix([[14]])

In [62]:
a*a.T/2 == 7

matrix([[ True]], dtype=bool)